export class WorkerError extends Error {
  constructor(public code: string, message: string) {
    super(message);
    this.name = 'WorkerError';
  }
}

export const WorkerErrorCodes = {
  SOURCE_NOT_READY: 'SOURCE_NOT_READY',
  SOURCE_DOWNLOAD_FAILED: 'SOURCE_DOWNLOAD_FAILED',
  AUDIO_EXTRACTION_FAILED: 'AUDIO_EXTRACTION_FAILED',
  PROVIDER_RATE_LIMITED: 'PROVIDER_RATE_LIMITED',
  PROVIDER_TIMEOUT: 'PROVIDER_TIMEOUT',
  PROVIDER_UNAVAILABLE: 'PROVIDER_UNAVAILABLE',
  SOURCE_NOT_FOUND: 'SOURCE_NOT_FOUND',
  AUDIO_TOO_LARGE: 'AUDIO_TOO_LARGE',
  PROVIDER_AUTHENTICATION_FAILED: 'PROVIDER_AUTHENTICATION_FAILED',
  PROVIDER_INVALID_RESPONSE: 'PROVIDER_INVALID_RESPONSE',
  TRANSCRIPT_NORMALISATION_FAILED: 'TRANSCRIPT_NORMALISATION_FAILED',
  TRANSCRIPT_VALIDATION_FAILED: 'TRANSCRIPT_VALIDATION_FAILED',
  INTERNAL_WORKER_ERROR: 'INTERNAL_WORKER_ERROR',
  LEASE_LOST: 'LEASE_LOST',
  CANCELLED: 'CANCELLED'
} as const;
