-- Fix User Progress Foreign Key to Cascade Delete
-- Run this in the Supabase SQL Editor

-- 1. Drop the existing constraint (if name is unknown, we try standard naming or generic approach)
-- Note: We assume the standard naming generated by Postgres or Supabase. 
-- Typically: user_progress_course_id_fkey

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'user_progress_course_id_fkey') THEN
    ALTER TABLE public.user_progress DROP CONSTRAINT user_progress_course_id_fkey;
  END IF;
END $$;

-- 2. Re-add the constraint with ON DELETE CASCADE
ALTER TABLE public.user_progress
ADD CONSTRAINT user_progress_course_id_fkey
FOREIGN KEY (course_id)
REFERENCES public.courses(id)
ON DELETE CASCADE;

-- Optional: Verify
-- SELECT * FROM information_schema.referential_constraints WHERE constraint_name = 'user_progress_course_id_fkey';
